Úpravy pro servírování z naučse
Glutexo/pyladies-piskvorky pull request #5
Opened 2019-02-25 12:57 UTC by frenzymadness

Trošku jsem to místy poupravil, aby to nebylo tak upovídané a dalo se to lépe začlenit přímo do naučse místo servírování z Githubu.

Ještě smažu seznam autorů, to se pak dá to `info.yml`.

Jsem otevřen diskusi.

2019-02-25 18:38 UTC, frenzymadness commented on README.md
> +1. Opět podle [návodu][testing] pytest spusť.
```suggestion
1. Opět podle Boooooooo [návodu][testing] pytest spusť.
```

2019-02-26 17:16 UTC, Glutexo requested changes
Dobrý den. Tož nějaké takzvané malichernosti k doplnění. Děkuji.

2019-02-26 17:16 UTC, Glutexo commented on README.md
> +1. Stáhni si připravený soubor pro [piškvorky] a [soubor s testy](testpiskvorky) a ulož je do samostatné složky.
```suggestion
1. Stáhni si připravený soubor pro [piškvorky] a [soubor s testy][testpiskvorky] a ulož je do samostatné složky.
```

2019-02-26 17:16 UTC, Glutexo commented on README.md
> +1. Aktivuj si své virtuální prostředí.
Proč tu máme všude jedničky místo postupného číslování?
```suggestion
2. Aktivuj si své virtuální prostředí.
```

2019-02-26 17:16 UTC, Glutexo commented on README.md
> +klidně postupuj jen podle zadání domácích projektů a na testování se společně podíváme později.
Držme jednotný styl dokumentu a nevkládejme náhodná odřádkování.

2019-02-26 17:16 UTC, Glutexo commented on README.md
> +1. Nainstaluj si knihovnu pytest podle [návodu][testing] v materiálech. Právě ta ti umožní ověřit správnou funkčnost programu.
```suggestion
3. Nainstaluj si knihovnu _pytest_ podle [návodu][testing] v materiálech. Právě ta ti umožní ověřit správnou funkčnost programu.
```

2019-02-26 17:16 UTC, Glutexo commented on piskvorky.py
> +     řetězec "x" když vyhraje hráč,
```suggestion
     řetězec "x", když vyhraje hráč,
```

2019-02-26 17:16 UTC, Glutexo commented on piskvorky.py
> +     řetězec "!" když dojde k remíze nebo
```suggestion
     řetězec "!", když dojde k remíze, nebo
```

2019-02-26 17:16 UTC, Glutexo commented on piskvorky.py
> +     řetězec "o" když vyhraje počítač,
```suggestion
     řetězec "o", když vyhraje počítač,
```

2019-02-26 17:16 UTC, Glutexo commented on piskvorky.py
> +     řetězec "-" když je možné ještě pokračovat ve hře
```suggestion
     řetězec "-", když je možné ještě pokračovat ve hře
```

2019-02-26 17:16 UTC, Glutexo commented on README.md
>  [Pytest] ti vypíše, kde všude v tvém programu narazil na problém. Tyto jsou podrobně rozepsané a výstup je tak trochu dlouhý. Na jeho začátku však budeš mít takovéto řádky:
```suggestion
Pytest ti vypíše, kde všude v tvém programu narazil na problém. Tyto jsou podrobně rozepsané a výstup je tak trochu dlouhý. Na jeho začátku však budeš mít takovéto řádky:
```

2019-02-26 17:16 UTC, Glutexo commented on README.md
>  [defstr]: https://naucse.python.cz/2019/pyladies-ostrava-jaro/sessions/def-str/
Když už odebíráme odkaz na _pytest_, odebral bych jej i tady ze seznamu – již není potřeba.

2019-02-26 17:16 UTC, Glutexo commented on piskvorky.py
> -#!/usr/bin/env python
• Když nechceme shebangy a tak se ani nesnažíme se tvářit jako samostatný projekt, rovnou bych odebral i _requirements.txt_.
• Bez shebangu by soubor neměl být spustitelný. Změnil bych oprávnění.

2019-02-26 17:26 UTC, Glutexo commented on README.md
>  ```shell
Všiml jsem si, že když to není odsazené, tak to ničí číslování potom po naformátování. To je moje chyba. Kdyžtak přihoď prosím odsazení.
```suggestion
```.  shell
```

2019-02-26 17:26 UTC, Glutexo commented on README.md
>  (venv) $ pip install pytest
```suggestion
   (venv) $ pip install pytest
```

2019-02-26 17:26 UTC, Glutexo commented on README.md
>  ```
```suggestion
   ```
```

2019-02-26 17:27 UTC, Glutexo commented on README.md
>  ```shell
```suggestion
   ```shell
```

2019-02-26 17:27 UTC, Glutexo commented on README.md
>  (venv) $ pytest -v test_piskvorky.py
```suggestion
   (venv) $ pytest -v test_piskvorky.py
```

2019-02-26 17:27 UTC, Glutexo commented on README.md
>  ```
```suggestion
   ```
```

2019-02-26 17:28 UTC, Glutexo commented on README.md
> +1. Opět podle [návodu][testing] pytest spusť.
```suggestion
3. Opět podle [návodu][testing] pytest spusť.
```

2019-02-27 11:01 UTC, frenzymadness commented on README.md
> +1. Aktivuj si své virtuální prostředí.
Protože markdown z jakéhokoli číslovaného seznamu udělá výstup v HTML takto:

```html
<ol>
<li></li>
<li></li>
<li></li>
</ol>
```
Takže na číslech ani jejich pořadí nezáleží. Seznam bude vždy číslován od jedničky po `n`. No a když jsou tam jen jedničky, je snadné pak něco přidat nebo smazat a není při tom třeba celý seznam přečíslovat.

2019-02-27 11:03 UTC, frenzymadness commented on README.md
> +klidně postupuj jen podle zadání domácích projektů a na testování se společně podíváme později.
Oukej, opravím.

2019-02-27 11:18 UTC, frenzymadness commented on README.md
>  [defstr]: https://naucse.python.cz/2019/pyladies-ostrava-jaro/sessions/def-str/
Neodebíral bych jej úplně, ale dáme jej jen na první zmínku o pytestu k instalaci, pak už není třeba se na něj znovu odkazovat.

2019-02-27 11:18 UTC, frenzymadness commented on piskvorky.py
> -#!/usr/bin/env python
Ok, opravím.

2019-02-27 11:20 UTC, frenzymadness commented on README.md
>  ```
Přidal jsem odsazení k blokům kódu v číslovaném seznamu.

2019-02-27 11:29 UTC, frenzymadness commented
Snad jsem opravil vše a vymotal jsem se ze všech konfliktů a sloučil jsem všechny úpravy zde navrhované do původních commitů.

2019-02-27 19:39 UTC, Glutexo requested changes
Ještě trocha konfliktů.

2019-02-27 19:39 UTC, Glutexo commented on README.md
> +1. Aktivuj si své virtuální prostředí.
Jedna z výhod Markdownu je, že je celkem pěkný a čitelný i neformátovaný. Ale chápu, nějak to rozdýchám. 😃

2019-02-27 19:39 UTC, Glutexo commented on piskvorky.py
> +<<<<<<< HEAD
💥

2019-02-27 19:39 UTC, Glutexo commented on piskvorky.py
> +=======
💥

2019-02-27 19:39 UTC, Glutexo commented on piskvorky.py
> +>>>>>>> ae881ce... Upraven popis pro servírování přímo jako materiál z naucse.python.cz
💥

2019-02-28 06:45 UTC, frenzymadness commented on piskvorky.py
> +<<<<<<< HEAD
Konflikt sice vyřešen, ale soubor neuložen. Díky, opraveno!

2019-03-04 15:57 UTC, merged

2019-03-04 15:57 UTC, Glutexo commented
Bezva. Vypadá to dobře. Potvrzuji, že i nové testy jsou zelené s mým řešením.